<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKI1WJl5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKI1WJl5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKI1WJl5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKI1WJl5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKI1WJl5\App_KernelDevDebugContainer([
    'container.build_hash' => 'KI1WJl5',
    'container.build_id' => 'b2dc982e',
    'container.build_time' => 1733247433,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKI1WJl5');
