<?php

namespace Container1wPQA2K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yOkfgpG.App\Controller\Api\TaskController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yOkfgpG.App\\Controller\\Api\\TaskController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'repository' => 'App\\Repository\\TaskRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\Api\\TaskController::update()', $container);
    }
}
