<?php

namespace ContainerKI1WJl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a.GwWBn.App\Controller\Api\TaskController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a.GwWBn.App\\Controller\\Api\\TaskController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\TaskRepository',
        ]))->withContext('App\\Controller\\Api\\TaskController::delete()', $container);
    }
}
